# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a5f65e4ad65a337db0c69001d40752a24725305e4e358e28e1552c80da17fded526389c25c23e6eecbd32c104122331fd04583ff839d08915d6dd4ffe4bbcb2

test:
  secret_key_base: 07b246460e013bc4c9c7a3a2b492b79766eb52c3868613e7909777976b95640f302aec2e40f521e01bb6cd0d68d394dbb5a8442df8113602a7e36cf446d26fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
